version: '3.8'

services:
  jekyll:
    image: jekyll/jekyll  # Use the official Jekyll Docker image
    command: sh -c "bundle install && jekyll serve --host 0.0.0.0"
    volumes:
      - .:/srv/jekyll
    ports:
      - '4000:4000'
    environment:
      - JEKYLL_ENV=development